spring:
  application:
    name: robot-diy-forum
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: ${DB_PASS}
  servlet:
    multipart:
      max-file-size: ${UPLOAD_MAX_SIZE:5MB}
      max-request-size: 10MB

server:
  port: ${SERVER_PORT}

mybatis-plus:
  type-enums-package: com.slz.demo.common.enumeration
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

auto-table:
  mode: update
  show-banner: true
  model-package: com.slz.demo.pojo.entity

jwt:
  secret: ${JWT_SECRET}
  expire: ${JWT_EXPIRE}

upload:
  path: ${UPLOAD_PATH}
  max-image-size: ${UPLOAD_MAX_SIZE}

logging:
  level:
    root: INFO
    com.slz.demo.server.mapper: DEBUG
