spring:
  application:
    name: robot-diy-forum
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8080

mybatis-plus:
  type-enums-package: com.slz.demo.common.enumeration
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

auto-table:
  mode: update
  show-banner: true
  model-package: com.slz.demo.pojo.entity

jwt:
  secret: ${jwt.secret}
  expire: ${jwt.expire}

upload:
  path: ${upload.path}
  max-image-size: ${upload.max-image-size}

logging:
  level:
    root: INFO
    com.slz.demo.server.mapper: DEBUG
