spring:
  datasource:
    host: 106.53.208.13
    port: 3306
    database: robot_diy_forum
    username: user_rdf
    password: yyy299

jwt:
  secret: robot-diy-forum_diy_forum2026slz
  expire: 86400000

upload:
  path: /ProjectFile/RobotDiyForumFile
  max-image-size: 5MB
